BAREBOX=barebox-2021.08.0
PACKAGE_BAREBOX=$BAREBOX.tar.bz2

UBOOT=u-boot-2021.07
PACKAGE_UBOOT=$UBOOT.tar.bz2

LINUX_KERNEL=linux-5.14.2
PACKAGE_LINUX_KERNEL=$LINUX_KERNEL.tar.xz

MUSL=musl-1.2.2
PACKAGE_MUSL=$MUSL.tar.gz

BUSYBOX=busybox-1.34.0
PACKAGE_BUSYBOX=$BUSYBOX.tar.bz2

GLIBC=glibc-2.34
PACKAGE_GLIBC=$GLIBC.tar.xz