BAREBOX=barebox-2022.01.0
PACKAGE_BAREBOX=$BAREBOX.tar.bz2

UBOOT=u-boot-2022.01
PACKAGE_UBOOT=$UBOOT.tar.bz2

LINUX_KERNEL=linux-5.16.9
PACKAGE_LINUX_KERNEL=$LINUX_KERNEL.tar.xz

MUSL=musl-1.2.2
PACKAGE_MUSL=$MUSL.tar.gz

BUSYBOX=busybox-1.35.0
PACKAGE_BUSYBOX=$BUSYBOX.tar.bz2

GLIBC=glibc-2.35
PACKAGE_GLIBC=$GLIBC.tar.xz

COREUTILS=coreutils-9.0
PACKAGE_COREUTILS=$COREUTILS.tar.xz

BASH=bash-5.1.16
PACKAGE_BASH=$BASH.tar.gz

SHADOW=shadow
SHADOW_VER=v4.11.1
