URL_BAREBOX="https://www.barebox.org/download"
URL_UBOOT="https://ftp.denx.de/pub/u-boot"
URL_LINUX_KERNEL="https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x"
URL_MUSL="https://musl.libc.org/releases"
URL_BUSYBOX="https://busybox.net/downloads"
URL_GLIBC="https://ftp.gnu.org/gnu/glibc"
